### ISSUE TITLE
[meta] extention list

### ISSUE THREAD

**Issue by Green-Sky** [toxext/toxext#10]
is there some form of extension list, including uuids?
collisions with 16bytes of uuid are very rare, but some kind of list would be nice.

**Comment by sphaerophoria** [comment]
No there's no central list, at this point toxext _may_ have written the only extensions, but we can't know for sure. I guess it does make sense to write down the ones we know we've taken somewhere, but we haven't done that. We're relying on the 16 byte uuid to be enough to prevent a collision.
