### ISSUE TITLE
Mock files are installed

### ISSUE THREAD

**Issue by sudden6** [toxext/toxext#4]
Doing `make`, `make test` and `sudo make install` leads to the following output:

```
-- Install configuration: ""
-- Installing: /usr/local/lib/cmake/ToxExt/ToxExtConfig.cmake
-- Installing: /usr/local/lib/cmake/ToxExt/ToxExtConfig-noconfig.cmake
-- Installing: /usr/local/lib/libtoxext.a
-- Installing: /usr/local/include/toxext/toxext.h
-- Up-to-date: /usr/local/include/toxext/toxext_util.h
-- Installing: /usr/local/lib/libtoxext_mock.a
-- Up-to-date: /usr/local/include/toxext/mock_fixtures.h
-- Up-to-date: /usr/local/include/toxext/mock_tox.h
```

It can be seen that mock files are installed, which are only used for testing.

**Comment by sphaerophoria** [comment]
I think I originally intentionally installed them so that the extensions could use the mocks for their testing as well. I guess the installation should be guarded with a cmake flag so they aren't installed on user systems.
